/**
 * Command Reference: every entry is a real command accepted by the
 * simulator's CLI (a test runs each example in its mode). `en` / `hi` are
 * one-line explanations. Syntax is the simulator's IOS-like CLI, not an
 * official vendor manual.
 */

export type RefMode =
  | 'user'
  | 'priv'
  | 'config'
  | 'config-if'
  | 'config-subif'
  | 'config-vlan'
  | 'config-router'
  | 'config-isis'
  | 'config-line'
  | 'host';
export type RefDevice = 'l2-switch' | 'l3-switch' | 'router' | 'pc';

export interface CommandRef {
  topic: string;
  example: string;
  mode: RefMode;
  device: RefDevice;
  en: string;
  hi: string;
  lesson?: string;
}

const sw = 'l2-switch' as const;
const l3 = 'l3-switch' as const;
const r = 'router' as const;
const pc = 'pc' as const;

export const COMMANDS: CommandRef[] = [
  // Basics
  {
    topic: 'Basics',
    example: 'enable',
    mode: 'user',
    device: sw,
    en: 'Enter privileged EXEC mode (#).',
    hi: 'Privileged mode mein jao.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'configure terminal',
    mode: 'priv',
    device: sw,
    en: 'Enter global configuration mode.',
    hi: 'Config mode mein jao.',
    lesson: 'A7',
  },
  { topic: 'Basics', example: 'hostname MTD-SW1', mode: 'config', device: sw, en: 'Set the device name.', hi: 'Device ka naam rakho.', lesson: 'A7' },
  {
    topic: 'Basics',
    example: 'end',
    mode: 'config-if',
    device: sw,
    en: 'Return to privileged EXEC from any config mode.',
    hi: 'Seedha # par wapas.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'show running-config',
    mode: 'priv',
    device: sw,
    en: 'Show the active configuration.',
    hi: 'Abhi ka config dikhao.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'write memory',
    mode: 'priv',
    device: sw,
    en: 'Save running-config to startup-config.',
    hi: 'Config save karo.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'copy running-config startup-config',
    mode: 'priv',
    device: sw,
    en: 'Same as write memory.',
    hi: 'Config save (doosra tareeka).',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'do show vlan brief',
    mode: 'config',
    device: sw,
    en: 'Run an EXEC command from config mode.',
    hi: 'Config mode se show chalao.',
    lesson: 'A7',
  },
  // Interfaces
  {
    topic: 'Interfaces',
    example: 'interface gi0/1',
    mode: 'config',
    device: sw,
    en: 'Select one interface to configure.',
    hi: 'Ek port chuno.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'interface range gi0/1 - 4',
    mode: 'config',
    device: sw,
    en: 'Configure several ports at once.',
    hi: 'Kai ports ek saath.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'description UTS counter 1',
    mode: 'config-if',
    device: sw,
    en: 'Label the interface.',
    hi: 'Port par label likho.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'shutdown',
    mode: 'config-if',
    device: sw,
    en: 'Administratively disable the port.',
    hi: 'Port band karo.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'no shutdown',
    mode: 'config-if',
    device: r,
    en: 'Enable the port (router ports start shut down).',
    hi: 'Port chalu karo (router ports default band).',
    lesson: 'A5',
  },
  {
    topic: 'Interfaces',
    example: 'duplex full',
    mode: 'config-if',
    device: sw,
    en: 'Force full duplex (both ends must match).',
    hi: 'Full duplex force (dono taraf same).',
    lesson: 'A4',
  },
  { topic: 'Interfaces', example: 'duplex auto', mode: 'config-if', device: sw, en: 'Back to auto-negotiation.', hi: 'Wapas auto.', lesson: 'A4' },
  {
    topic: 'Interfaces',
    example: 'show interfaces status',
    mode: 'priv',
    device: sw,
    en: 'One line per port: status, VLAN, duplex, speed.',
    hi: 'Har port ki ek line.',
    lesson: 'A4',
  },
  {
    topic: 'Interfaces',
    example: 'show interfaces gi0/1',
    mode: 'priv',
    device: sw,
    en: 'Detail of one port incl. errors.',
    hi: 'Ek port ki detail, errors ke saath.',
    lesson: 'A4',
  },
  // VLANs
  {
    topic: 'VLAN & trunk',
    example: 'vlan 10',
    mode: 'config',
    device: sw,
    en: 'Create VLAN 10 and enter VLAN config.',
    hi: 'VLAN 10 banao.',
    lesson: 'A7',
  },
  { topic: 'VLAN & trunk', example: 'name UTS', mode: 'config-vlan', device: sw, en: 'Name the VLAN.', hi: 'VLAN ka naam.', lesson: 'A7' },
  {
    topic: 'VLAN & trunk',
    example: 'switchport mode access',
    mode: 'config-if',
    device: sw,
    en: 'Make the port an access port.',
    hi: 'Port ko access banao.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport access vlan 10',
    mode: 'config-if',
    device: sw,
    en: 'Put the access port in VLAN 10.',
    hi: 'Access port ko VLAN 10 mein daalo.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport mode trunk',
    mode: 'config-if',
    device: sw,
    en: 'Make the port an 802.1Q trunk.',
    hi: 'Port ko trunk banao.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport trunk allowed vlan 10,20,40',
    mode: 'config-if',
    device: sw,
    en: 'Limit the VLANs on a trunk.',
    hi: 'Trunk par sirf yeh VLANs.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport trunk allowed vlan add 60',
    mode: 'config-if',
    device: sw,
    en: 'Add a VLAN to the allowed list.',
    hi: 'Allowed list mein VLAN jodo.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport trunk native vlan 99',
    mode: 'config-if',
    device: sw,
    en: 'Set the untagged (native) VLAN.',
    hi: 'Native VLAN set karo.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'show vlan brief',
    mode: 'priv',
    device: sw,
    en: 'VLANs and their access ports.',
    hi: 'VLANs aur unke ports.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'show interfaces trunk',
    mode: 'priv',
    device: sw,
    en: 'Trunk ports, native and allowed VLANs.',
    hi: 'Trunks ki detail.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'show mac address-table',
    mode: 'priv',
    device: sw,
    en: 'Learned MAC addresses per VLAN and port.',
    hi: 'Seekhe hue MACs.',
    lesson: 'A4',
  },
  {
    topic: 'VLAN & trunk',
    example: 'clear mac address-table dynamic',
    mode: 'priv',
    device: sw,
    en: 'Flush dynamically learned MACs.',
    hi: 'Seekhe hue MACs saaf karo.',
    lesson: 'A4',
  },
  // STP
  {
    topic: 'Spanning tree',
    example: 'spanning-tree vlan 1 priority 4096',
    mode: 'config',
    device: sw,
    en: 'Lower the bridge priority (make this the root).',
    hi: 'Priority kam karo — root banao.',
    lesson: 'A8',
  },
  {
    topic: 'Spanning tree',
    example: 'show spanning-tree',
    mode: 'priv',
    device: sw,
    en: 'Root, costs, port roles and states.',
    hi: 'Root aur port roles dikhao.',
    lesson: 'A8',
  },
  // EtherChannel
  {
    topic: 'EtherChannel',
    example: 'channel-group 1 mode active',
    mode: 'config-if',
    device: sw,
    en: 'Bundle the port into Port-channel 1 with LACP (active).',
    hi: 'Port ko LACP bundle mein daalo.',
    lesson: 'A8',
  },
  {
    topic: 'EtherChannel',
    example: 'channel-group 1 mode passive',
    mode: 'config-if',
    device: sw,
    en: 'LACP passive: answer only.',
    hi: 'LACP passive: sirf jawab.',
    lesson: 'A8',
  },
  {
    topic: 'EtherChannel',
    example: 'interface port-channel 1',
    mode: 'config',
    device: sw,
    en: 'Configure the bundle; L2 settings copy to members.',
    hi: 'Bundle ka config — members par copy.',
    lesson: 'A8',
  },
  {
    topic: 'EtherChannel',
    example: 'show etherchannel summary',
    mode: 'priv',
    device: sw,
    en: 'Bundles and member flags (P/I/s/D).',
    hi: 'Bundles aur member flags.',
    lesson: 'A8',
  },
  // Port security
  {
    topic: 'Port security',
    example: 'switchport port-security',
    mode: 'config-if',
    device: sw,
    en: 'Enable port security (default max 1, shutdown).',
    hi: 'Port security chalu.',
    lesson: 'A8',
  },
  {
    topic: 'Port security',
    example: 'switchport port-security maximum 2',
    mode: 'config-if',
    device: sw,
    en: 'Allow up to 2 MACs.',
    hi: '2 MAC tak allowed.',
    lesson: 'A8',
  },
  {
    topic: 'Port security',
    example: 'switchport port-security violation restrict',
    mode: 'config-if',
    device: sw,
    en: 'Drop + count instead of shutting the port.',
    hi: 'Port band nahi, sirf drop.',
    lesson: 'A8',
  },
  {
    topic: 'Port security',
    example: 'show port-security',
    mode: 'priv',
    device: sw,
    en: 'Secure ports and violation counts.',
    hi: 'Secure ports aur violations.',
    lesson: 'A8',
  },
  // IP
  {
    topic: 'IP',
    example: 'ip address 10.52.1.1 255.255.255.0',
    mode: 'config-if',
    device: r,
    en: 'Set the interface IPv4 address.',
    hi: 'Interface ko IP do.',
    lesson: 'A5',
  },
  {
    topic: 'IP',
    example: 'show ip interface brief',
    mode: 'priv',
    device: r,
    en: 'Interfaces with IP, status and protocol.',
    hi: 'Interfaces aur unke IP.',
    lesson: 'A5',
  },
  { topic: 'IP', example: 'show arp', mode: 'priv', device: r, en: 'IP → MAC mappings learned by ARP.', hi: 'ARP table.', lesson: 'A5' },
  { topic: 'IP', example: 'show ip route', mode: 'priv', device: r, en: 'Routing table.', hi: 'Routing table.', lesson: 'A9' },
  { topic: 'IP', example: 'ping 10.52.1.11', mode: 'priv', device: r, en: 'Send ICMP echo requests.', hi: 'Ping bhejo.', lesson: 'A5' },
  {
    topic: 'IP',
    example: 'traceroute 10.52.1.11',
    mode: 'priv',
    device: r,
    en: 'Show the hops to a destination.',
    hi: 'Raste ke hops dikhao.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'ip routing',
    mode: 'config',
    device: l3,
    en: 'Turn on routing on an L3 switch.',
    hi: 'L3 switch par routing on.',
    lesson: 'A9',
  },
  // Host
  {
    topic: 'Host (PC)',
    example: 'ipconfig /all',
    mode: 'host',
    device: pc,
    en: 'IP, mask, gateway, MAC and DHCP info.',
    hi: 'PC ki IP settings.',
    lesson: 'A5',
  },
  { topic: 'Host (PC)', example: 'ping 10.52.1.1', mode: 'host', device: pc, en: 'Ping from the PC.', hi: 'PC se ping.', lesson: 'A5' },
  {
    topic: 'Host (PC)',
    example: 'tracert 10.52.1.1',
    mode: 'host',
    device: pc,
    en: 'Trace the route from the PC.',
    hi: 'PC se route trace.',
    lesson: 'A9',
  },
  { topic: 'Host (PC)', example: 'arp -a', mode: 'host', device: pc, en: 'Show the PC’s ARP cache.', hi: 'PC ki ARP cache.', lesson: 'A5' },
  // Phase 3: routing, services, security, redundancy, QoS
  {
    topic: 'IP',
    example: 'interface gi0/0.10',
    mode: 'config',
    device: r,
    en: 'Create a sub-interface (router-on-a-stick).',
    hi: 'Sub-interface banao.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'encapsulation dot1Q 10',
    mode: 'config-subif',
    device: r,
    en: '(on a sub-interface) Take frames tagged with VLAN 10.',
    hi: 'VLAN 10 ke tagged frames lo.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'ip route 0.0.0.0 0.0.0.0 10.255.0.1',
    mode: 'config',
    device: r,
    en: 'Default route towards a next hop.',
    hi: 'Default route.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'interface loopback0',
    mode: 'config',
    device: r,
    en: 'Create a loopback (always-up router address).',
    hi: 'Loopback banao.',
    lesson: 'A10',
  },
  { topic: 'OSPF', example: 'router ospf 1', mode: 'config', device: r, en: 'Start OSPF process 1.', hi: 'OSPF chalu karo.', lesson: 'A10' },
  {
    topic: 'OSPF',
    example: 'network 10.0.0.0 0.255.255.255 area 0',
    mode: 'config-router',
    device: r,
    en: 'Run OSPF on matching interfaces in area 0.',
    hi: 'In interfaces par OSPF area 0.',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'default-information originate',
    mode: 'config-router',
    device: r,
    en: 'Advertise this router’s default route into OSPF.',
    hi: 'Default route OSPF mein bhejo.',
    lesson: 'A15',
  },
  {
    topic: 'OSPF',
    example: 'ip ospf cost 100',
    mode: 'config-if',
    device: r,
    en: 'Set the OSPF cost of this interface.',
    hi: 'Interface ki OSPF cost.',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'ip ospf hello-interval 10',
    mode: 'config-if',
    device: r,
    en: 'Set the OSPF hello timer (must match the neighbour).',
    hi: 'Hello timer (neighbour se match).',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'show ip ospf neighbor',
    mode: 'priv',
    device: r,
    en: 'OSPF neighbours and their state (FULL = synced).',
    hi: 'OSPF neighbours aur state.',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'show ip ospf interface gi0/1',
    mode: 'priv',
    device: r,
    en: 'OSPF settings per interface (cost, timers, DR).',
    hi: 'Har interface ki OSPF settings.',
    lesson: 'A10',
  },
  { topic: 'IS-IS', example: 'router isis', mode: 'config', device: r, en: 'Start IS-IS.', hi: 'IS-IS chalu karo.', lesson: 'A10' },
  {
    topic: 'IS-IS',
    example: 'net 49.0001.0000.0000.0001.00',
    mode: 'config-isis',
    device: r,
    en: 'Set the NET (area + system ID).',
    hi: 'NET address (area + system ID).',
    lesson: 'A10',
  },
  {
    topic: 'IS-IS',
    example: 'ip router isis',
    mode: 'config-if',
    device: r,
    en: 'Run IS-IS on this interface.',
    hi: 'Is interface par IS-IS.',
    lesson: 'A10',
  },
  {
    topic: 'IS-IS',
    example: 'show isis neighbors',
    mode: 'priv',
    device: r,
    en: 'IS-IS adjacencies with level (L1/L2).',
    hi: 'IS-IS neighbours aur level.',
    lesson: 'A10',
  },
  {
    topic: 'Services',
    example: 'ip helper-address 10.1.1.53',
    mode: 'config-if',
    device: r,
    en: 'DHCP relay: forward client broadcasts to this server.',
    hi: 'DHCP relay — server tak bhejo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ip nat inside',
    mode: 'config-if',
    device: r,
    en: 'Mark the interface as NAT inside.',
    hi: 'NAT inside interface.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ip nat outside',
    mode: 'config-if',
    device: r,
    en: 'Mark the interface as NAT outside.',
    hi: 'NAT outside interface.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ip nat inside source list 1 interface gi0/2 overload',
    mode: 'config',
    device: r,
    en: 'PAT: translate ACL 1 sources to the Gi0/2 address.',
    hi: 'PAT: ACL 1 ko Gi0/2 address se badlo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'show ip nat translations',
    mode: 'priv',
    device: r,
    en: 'Current NAT/PAT translations.',
    hi: 'NAT translations.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ntp server 10.1.1.53',
    mode: 'config',
    device: r,
    en: 'Sync the clock from an NTP server.',
    hi: 'NTP server se time lo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'show ntp status',
    mode: 'priv',
    device: r,
    en: 'Is the clock synchronised, at which stratum?',
    hi: 'Clock sync hai? stratum?',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'logging host 10.1.1.100',
    mode: 'config',
    device: r,
    en: 'Send syslog messages to a server.',
    hi: 'Syslog server ko bhejo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'snmp-server enable traps',
    mode: 'config',
    device: r,
    en: 'Send SNMP traps (with snmp-server host).',
    hi: 'SNMP traps bhejo.',
    lesson: 'A11',
  },
  {
    topic: 'Security',
    example: 'access-list 110 deny ip 10.52.50.0 0.0.0.255 10.52.10.0 0.0.0.255',
    mode: 'config',
    device: r,
    en: 'Extended ACL line: block one subnet to another.',
    hi: 'Extended ACL: ek subnet se doosre ko roko.',
    lesson: 'A12',
  },
  {
    topic: 'Security',
    example: 'ip access-group 110 in',
    mode: 'config-if',
    device: r,
    en: 'Apply ACL 110 to packets entering the interface.',
    hi: 'ACL 110 inbound lagao.',
    lesson: 'A12',
  },
  { topic: 'Security', example: 'show access-lists', mode: 'priv', device: r, en: 'List ACLs and their lines.', hi: 'ACLs dikhao.', lesson: 'A12' },
  {
    topic: 'Security',
    example: 'crypto key generate rsa modulus 2048',
    mode: 'config',
    device: r,
    en: 'Create RSA keys for SSH (needs ip domain-name).',
    hi: 'SSH ke liye RSA keys.',
    lesson: 'A11',
  },
  {
    topic: 'Security',
    example: 'transport input ssh',
    mode: 'config-line',
    device: r,
    en: 'Allow only SSH on the vty lines.',
    hi: 'vty par sirf SSH.',
    lesson: 'A12',
  },
  {
    topic: 'Security',
    example: 'login local',
    mode: 'config-line',
    device: r,
    en: 'Use local usernames for vty logins.',
    hi: 'Local usernames se login.',
    lesson: 'A12',
  },
  {
    topic: 'Security',
    example: 'access-class 10 in',
    mode: 'config-line',
    device: r,
    en: 'Only addresses permitted by ACL 10 may log in.',
    hi: 'Sirf ACL 10 wale login kar sakte.',
    lesson: 'A12',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 ip 10.52.10.1',
    mode: 'config-if',
    device: r,
    en: 'HSRP group 10 with this virtual gateway IP.',
    hi: 'HSRP group 10 ka virtual IP.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 priority 110',
    mode: 'config-if',
    device: r,
    en: 'HSRP priority (higher = Active).',
    hi: 'HSRP priority.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 preempt',
    mode: 'config-if',
    device: r,
    en: 'Take the Active role back when better.',
    hi: 'Behtar ho to role wapas lo.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 track gi0/1 decrement 20',
    mode: 'config-if',
    device: r,
    en: 'Lower priority by 20 when Gi0/1 goes down.',
    hi: 'Gi0/1 gire to priority 20 kam.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'show standby brief',
    mode: 'priv',
    device: r,
    en: 'HSRP groups, priority and state.',
    hi: 'HSRP state.',
    lesson: 'A13',
  },
  {
    topic: 'QoS',
    example: 'class-map match-any VOICE',
    mode: 'config',
    device: r,
    en: 'Create a traffic class.',
    hi: 'Traffic class banao.',
    lesson: 'A14',
  },
  {
    topic: 'QoS',
    example: 'policy-map WAN-OUT',
    mode: 'config',
    device: r,
    en: 'Create a QoS policy (then class / priority / bandwidth).',
    hi: 'QoS policy banao.',
    lesson: 'A14',
  },
  {
    topic: 'QoS',
    example: 'service-policy output WAN-OUT',
    mode: 'config-if',
    device: r,
    en: 'Attach the policy to outgoing traffic.',
    hi: 'Policy outgoing par lagao.',
    lesson: 'A14',
  },
  { topic: 'QoS', example: 'speed 10', mode: 'config-if', device: r, en: 'Force the port speed (Mb/s).', hi: 'Port speed fix karo.', lesson: 'A14' },
  {
    topic: 'Host (PC)',
    example: 'nslookup ju-nms',
    mode: 'host',
    device: pc,
    en: 'Ask the DNS server for a name.',
    hi: 'DNS se naam poochho.',
    lesson: 'A11',
  },
  {
    topic: 'Host (PC)',
    example: 'ssh admin@10.1.1.1',
    mode: 'host',
    device: pc,
    en: 'Open an SSH connection (connection + login check).',
    hi: 'SSH connection kholo.',
    lesson: 'A11',
  },
  {
    topic: 'Host (PC)',
    example: 'ipconfig /renew',
    mode: 'host',
    device: pc,
    en: 'Get a DHCP address again.',
    hi: 'DHCP se address dobara lo.',
    lesson: 'A11',
  },
];

/** CLI lines that bring a fresh device into `mode` (used by the reference test and the "try it" hint). */
export function preLines(mode: RefMode, device: RefDevice): string[] {
  const port = device === 'router' ? 'gi0/0' : device === 'l3-switch' ? 'gi1/0/1' : 'gi0/1';
  switch (mode) {
    case 'user':
    case 'host':
      return [];
    case 'priv':
      return ['enable'];
    case 'config':
      return ['enable', 'configure terminal'];
    case 'config-if':
      return ['enable', 'configure terminal', `interface ${port}`];
    case 'config-vlan':
      return ['enable', 'configure terminal', 'vlan 10'];
    case 'config-router':
      return ['enable', 'configure terminal', 'router ospf 1'];
    case 'config-subif':
      return ['enable', 'configure terminal', 'interface gi0/0.10'];
    case 'config-isis':
      return ['enable', 'configure terminal', 'router isis'];
    case 'config-line':
      return ['enable', 'configure terminal', 'line vty 0 4'];
  }
}
