/**
 * Command Reference: every entry is a real command accepted by the
 * simulator's CLI (a test runs each example in its mode). `en` / `hi` are
 * one-line explanations. Syntax is the simulator's IOS-like CLI, not an
 * official vendor manual.
 */

export type RefMode =
  | 'user'
  | 'priv'
  | 'config'
  | 'config-if'
  | 'config-subif'
  | 'config-vlan'
  | 'config-router'
  | 'config-isis'
  | 'config-line'
  | 'config-vrf'
  | 'config-vrf-af'
  | 'config-bgp'
  | 'config-bgp-vpnv4'
  | 'config-bgp-vrf'
  | 'config-vfi'
  | 'config-controller'
  | 'config-cem-if'
  | 'config-if-cem'
  | 'host';
export type RefDevice = 'l2-switch' | 'l3-switch' | 'router' | 'pc' | 'neon-ler';

export interface CommandRef {
  topic: string;
  example: string;
  mode: RefMode;
  device: RefDevice;
  en: string;
  hi: string;
  lesson?: string;
}

const sw = 'l2-switch' as const;
const l3 = 'l3-switch' as const;
const r = 'router' as const;
const pc = 'pc' as const;
const ler = 'neon-ler' as const;

export const COMMANDS: CommandRef[] = [
  // Basics
  {
    topic: 'Basics',
    example: 'enable',
    mode: 'user',
    device: sw,
    en: 'Enter privileged EXEC mode (#).',
    hi: 'Privileged mode mein jao.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'configure terminal',
    mode: 'priv',
    device: sw,
    en: 'Enter global configuration mode.',
    hi: 'Config mode mein jao.',
    lesson: 'A7',
  },
  { topic: 'Basics', example: 'hostname MTD-SW1', mode: 'config', device: sw, en: 'Set the device name.', hi: 'Device ka naam rakho.', lesson: 'A7' },
  {
    topic: 'Basics',
    example: 'end',
    mode: 'config-if',
    device: sw,
    en: 'Return to privileged EXEC from any config mode.',
    hi: 'Seedha # par wapas.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'show running-config',
    mode: 'priv',
    device: sw,
    en: 'Show the active configuration.',
    hi: 'Abhi ka config dikhao.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'write memory',
    mode: 'priv',
    device: sw,
    en: 'Save running-config to startup-config.',
    hi: 'Config save karo.',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'copy running-config startup-config',
    mode: 'priv',
    device: sw,
    en: 'Same as write memory.',
    hi: 'Config save (doosra tareeka).',
    lesson: 'A7',
  },
  {
    topic: 'Basics',
    example: 'do show vlan brief',
    mode: 'config',
    device: sw,
    en: 'Run an EXEC command from config mode.',
    hi: 'Config mode se show chalao.',
    lesson: 'A7',
  },
  // Interfaces
  {
    topic: 'Interfaces',
    example: 'interface gi0/1',
    mode: 'config',
    device: sw,
    en: 'Select one interface to configure.',
    hi: 'Ek port chuno.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'interface range gi0/1 - 4',
    mode: 'config',
    device: sw,
    en: 'Configure several ports at once.',
    hi: 'Kai ports ek saath.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'description UTS counter 1',
    mode: 'config-if',
    device: sw,
    en: 'Label the interface.',
    hi: 'Port par label likho.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'shutdown',
    mode: 'config-if',
    device: sw,
    en: 'Administratively disable the port.',
    hi: 'Port band karo.',
    lesson: 'A7',
  },
  {
    topic: 'Interfaces',
    example: 'no shutdown',
    mode: 'config-if',
    device: r,
    en: 'Enable the port (router ports start shut down).',
    hi: 'Port chalu karo (router ports default band).',
    lesson: 'A5',
  },
  {
    topic: 'Interfaces',
    example: 'duplex full',
    mode: 'config-if',
    device: sw,
    en: 'Force full duplex (both ends must match).',
    hi: 'Full duplex force (dono taraf same).',
    lesson: 'A4',
  },
  { topic: 'Interfaces', example: 'duplex auto', mode: 'config-if', device: sw, en: 'Back to auto-negotiation.', hi: 'Wapas auto.', lesson: 'A4' },
  {
    topic: 'Interfaces',
    example: 'show interfaces status',
    mode: 'priv',
    device: sw,
    en: 'One line per port: status, VLAN, duplex, speed.',
    hi: 'Har port ki ek line.',
    lesson: 'A4',
  },
  {
    topic: 'Interfaces',
    example: 'show interfaces gi0/1',
    mode: 'priv',
    device: sw,
    en: 'Detail of one port incl. errors.',
    hi: 'Ek port ki detail, errors ke saath.',
    lesson: 'A4',
  },
  // VLANs
  {
    topic: 'VLAN & trunk',
    example: 'vlan 10',
    mode: 'config',
    device: sw,
    en: 'Create VLAN 10 and enter VLAN config.',
    hi: 'VLAN 10 banao.',
    lesson: 'A7',
  },
  { topic: 'VLAN & trunk', example: 'name UTS', mode: 'config-vlan', device: sw, en: 'Name the VLAN.', hi: 'VLAN ka naam.', lesson: 'A7' },
  {
    topic: 'VLAN & trunk',
    example: 'switchport mode access',
    mode: 'config-if',
    device: sw,
    en: 'Make the port an access port.',
    hi: 'Port ko access banao.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport access vlan 10',
    mode: 'config-if',
    device: sw,
    en: 'Put the access port in VLAN 10.',
    hi: 'Access port ko VLAN 10 mein daalo.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport mode trunk',
    mode: 'config-if',
    device: sw,
    en: 'Make the port an 802.1Q trunk.',
    hi: 'Port ko trunk banao.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport trunk allowed vlan 10,20,40',
    mode: 'config-if',
    device: sw,
    en: 'Limit the VLANs on a trunk.',
    hi: 'Trunk par sirf yeh VLANs.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport trunk allowed vlan add 60',
    mode: 'config-if',
    device: sw,
    en: 'Add a VLAN to the allowed list.',
    hi: 'Allowed list mein VLAN jodo.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'switchport trunk native vlan 99',
    mode: 'config-if',
    device: sw,
    en: 'Set the untagged (native) VLAN.',
    hi: 'Native VLAN set karo.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'show vlan brief',
    mode: 'priv',
    device: sw,
    en: 'VLANs and their access ports.',
    hi: 'VLANs aur unke ports.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'show interfaces trunk',
    mode: 'priv',
    device: sw,
    en: 'Trunk ports, native and allowed VLANs.',
    hi: 'Trunks ki detail.',
    lesson: 'A7',
  },
  {
    topic: 'VLAN & trunk',
    example: 'show mac address-table',
    mode: 'priv',
    device: sw,
    en: 'Learned MAC addresses per VLAN and port.',
    hi: 'Seekhe hue MACs.',
    lesson: 'A4',
  },
  {
    topic: 'VLAN & trunk',
    example: 'clear mac address-table dynamic',
    mode: 'priv',
    device: sw,
    en: 'Flush dynamically learned MACs.',
    hi: 'Seekhe hue MACs saaf karo.',
    lesson: 'A4',
  },
  // STP
  {
    topic: 'Spanning tree',
    example: 'spanning-tree vlan 1 priority 4096',
    mode: 'config',
    device: sw,
    en: 'Lower the bridge priority (make this the root).',
    hi: 'Priority kam karo — root banao.',
    lesson: 'A8',
  },
  {
    topic: 'Spanning tree',
    example: 'show spanning-tree',
    mode: 'priv',
    device: sw,
    en: 'Root, costs, port roles and states.',
    hi: 'Root aur port roles dikhao.',
    lesson: 'A8',
  },
  // EtherChannel
  {
    topic: 'EtherChannel',
    example: 'channel-group 1 mode active',
    mode: 'config-if',
    device: sw,
    en: 'Bundle the port into Port-channel 1 with LACP (active).',
    hi: 'Port ko LACP bundle mein daalo.',
    lesson: 'A8',
  },
  {
    topic: 'EtherChannel',
    example: 'channel-group 1 mode passive',
    mode: 'config-if',
    device: sw,
    en: 'LACP passive: answer only.',
    hi: 'LACP passive: sirf jawab.',
    lesson: 'A8',
  },
  {
    topic: 'EtherChannel',
    example: 'interface port-channel 1',
    mode: 'config',
    device: sw,
    en: 'Configure the bundle; L2 settings copy to members.',
    hi: 'Bundle ka config — members par copy.',
    lesson: 'A8',
  },
  {
    topic: 'EtherChannel',
    example: 'show etherchannel summary',
    mode: 'priv',
    device: sw,
    en: 'Bundles and member flags (P/I/s/D).',
    hi: 'Bundles aur member flags.',
    lesson: 'A8',
  },
  // Port security
  {
    topic: 'Port security',
    example: 'switchport port-security',
    mode: 'config-if',
    device: sw,
    en: 'Enable port security (default max 1, shutdown).',
    hi: 'Port security chalu.',
    lesson: 'A8',
  },
  {
    topic: 'Port security',
    example: 'switchport port-security maximum 2',
    mode: 'config-if',
    device: sw,
    en: 'Allow up to 2 MACs.',
    hi: '2 MAC tak allowed.',
    lesson: 'A8',
  },
  {
    topic: 'Port security',
    example: 'switchport port-security violation restrict',
    mode: 'config-if',
    device: sw,
    en: 'Drop + count instead of shutting the port.',
    hi: 'Port band nahi, sirf drop.',
    lesson: 'A8',
  },
  {
    topic: 'Port security',
    example: 'show port-security',
    mode: 'priv',
    device: sw,
    en: 'Secure ports and violation counts.',
    hi: 'Secure ports aur violations.',
    lesson: 'A8',
  },
  // IP
  {
    topic: 'IP',
    example: 'ip address 10.52.1.1 255.255.255.0',
    mode: 'config-if',
    device: r,
    en: 'Set the interface IPv4 address.',
    hi: 'Interface ko IP do.',
    lesson: 'A5',
  },
  {
    topic: 'IP',
    example: 'show ip interface brief',
    mode: 'priv',
    device: r,
    en: 'Interfaces with IP, status and protocol.',
    hi: 'Interfaces aur unke IP.',
    lesson: 'A5',
  },
  { topic: 'IP', example: 'show arp', mode: 'priv', device: r, en: 'IP → MAC mappings learned by ARP.', hi: 'ARP table.', lesson: 'A5' },
  { topic: 'IP', example: 'show ip route', mode: 'priv', device: r, en: 'Routing table.', hi: 'Routing table.', lesson: 'A9' },
  { topic: 'IP', example: 'ping 10.52.1.11', mode: 'priv', device: r, en: 'Send ICMP echo requests.', hi: 'Ping bhejo.', lesson: 'A5' },
  {
    topic: 'IP',
    example: 'traceroute 10.52.1.11',
    mode: 'priv',
    device: r,
    en: 'Show the hops to a destination.',
    hi: 'Raste ke hops dikhao.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'ip routing',
    mode: 'config',
    device: l3,
    en: 'Turn on routing on an L3 switch.',
    hi: 'L3 switch par routing on.',
    lesson: 'A9',
  },
  // Host
  {
    topic: 'Host (PC)',
    example: 'ipconfig /all',
    mode: 'host',
    device: pc,
    en: 'IP, mask, gateway, MAC and DHCP info.',
    hi: 'PC ki IP settings.',
    lesson: 'A5',
  },
  { topic: 'Host (PC)', example: 'ping 10.52.1.1', mode: 'host', device: pc, en: 'Ping from the PC.', hi: 'PC se ping.', lesson: 'A5' },
  {
    topic: 'Host (PC)',
    example: 'tracert 10.52.1.1',
    mode: 'host',
    device: pc,
    en: 'Trace the route from the PC.',
    hi: 'PC se route trace.',
    lesson: 'A9',
  },
  { topic: 'Host (PC)', example: 'arp -a', mode: 'host', device: pc, en: 'Show the PC’s ARP cache.', hi: 'PC ki ARP cache.', lesson: 'A5' },
  // Phase 4: MPLS / LDP
  {
    topic: 'MPLS',
    example: 'mpls ip',
    mode: 'config-if',
    device: r,
    en: 'Enable label switching and LDP hellos on this interface.',
    hi: 'Is interface par MPLS/LDP chalu.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'mpls ldp router-id loopback0 force',
    mode: 'config',
    device: r,
    en: 'Use Loopback0 as the LDP router-ID (transport address).',
    hi: 'LDP router-ID = Loopback0.',
    lesson: 'B4',
  },
  {
    topic: 'MPLS',
    example: 'mpls ldp explicit-null',
    mode: 'config',
    device: r,
    en: 'Advertise label 0 instead of implicit-null for own prefixes (no PHP).',
    hi: 'PHP ki jagah label 0.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'no mpls ip propagate-ttl',
    mode: 'config',
    device: r,
    en: 'Do not copy IP TTL into labels: core hops hidden from traceroute.',
    hi: 'Core ko traceroute se chhupao.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'mpls ldp autoconfig',
    mode: 'config-router',
    device: r,
    en: '(router ospf) Enable MPLS/LDP on every OSPF interface.',
    hi: 'Sab OSPF interfaces par MPLS.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'mpls ldp sync',
    mode: 'config-router',
    device: r,
    en: '(router ospf) Max OSPF cost on links whose LDP session is down.',
    hi: 'LDP down link ko max cost.',
    lesson: 'B4',
  },
  {
    topic: 'MPLS',
    example: 'show mpls interfaces',
    mode: 'priv',
    device: r,
    en: 'Interfaces with MPLS and whether they are operational.',
    hi: 'MPLS wale interfaces.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'show mpls ldp neighbor',
    mode: 'priv',
    device: r,
    en: 'LDP sessions (peers, state, discovery sources, addresses).',
    hi: 'LDP neighbours.',
    lesson: 'B4',
  },
  {
    topic: 'MPLS',
    example: 'show mpls ldp discovery',
    mode: 'priv',
    device: r,
    en: 'Where LDP hellos are sent / received.',
    hi: 'LDP hellos kahan.',
    lesson: 'B4',
  },
  {
    topic: 'MPLS',
    example: 'show mpls ldp bindings',
    mode: 'priv',
    device: r,
    en: 'LIB: local and remote labels per prefix.',
    hi: 'LIB — sab labels.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'show mpls forwarding-table',
    mode: 'priv',
    device: r,
    en: 'LFIB: in label, out label (or Pop/No Label), next hop.',
    hi: 'LFIB — forwarding labels.',
    lesson: 'B3',
  },
  {
    topic: 'MPLS',
    example: 'show mpls ldp igp sync',
    mode: 'priv',
    device: r,
    en: 'LDP-IGP synchronization state per interface.',
    hi: 'LDP-IGP sync ki haalat.',
    lesson: 'B4',
  },
  {
    topic: 'MPLS',
    example: 'ping mpls ipv4 10.0.2.6/32',
    mode: 'priv',
    device: r,
    en: 'LSP ping: MPLS echo along the label path to a FEC.',
    hi: 'Label path ka ping.',
    lesson: 'B4',
  },
  {
    topic: 'MPLS',
    example: 'traceroute mpls ipv4 10.0.2.6/32',
    mode: 'priv',
    device: r,
    en: 'LSP traceroute: each hop of the label path.',
    hi: 'Label path ka traceroute.',
    lesson: 'B4',
  },
  // Phase 3: routing, services, security, redundancy, QoS
  {
    topic: 'IP',
    example: 'interface gi0/0.10',
    mode: 'config',
    device: r,
    en: 'Create a sub-interface (router-on-a-stick).',
    hi: 'Sub-interface banao.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'encapsulation dot1Q 10',
    mode: 'config-subif',
    device: r,
    en: '(on a sub-interface) Take frames tagged with VLAN 10.',
    hi: 'VLAN 10 ke tagged frames lo.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'ip route 0.0.0.0 0.0.0.0 10.255.0.1',
    mode: 'config',
    device: r,
    en: 'Default route towards a next hop.',
    hi: 'Default route.',
    lesson: 'A9',
  },
  {
    topic: 'IP',
    example: 'interface loopback0',
    mode: 'config',
    device: r,
    en: 'Create a loopback (always-up router address).',
    hi: 'Loopback banao.',
    lesson: 'A10',
  },
  { topic: 'OSPF', example: 'router ospf 1', mode: 'config', device: r, en: 'Start OSPF process 1.', hi: 'OSPF chalu karo.', lesson: 'A10' },
  {
    topic: 'OSPF',
    example: 'network 10.0.0.0 0.255.255.255 area 0',
    mode: 'config-router',
    device: r,
    en: 'Run OSPF on matching interfaces in area 0.',
    hi: 'In interfaces par OSPF area 0.',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'default-information originate',
    mode: 'config-router',
    device: r,
    en: 'Advertise this router’s default route into OSPF.',
    hi: 'Default route OSPF mein bhejo.',
    lesson: 'A15',
  },
  {
    topic: 'OSPF',
    example: 'ip ospf cost 100',
    mode: 'config-if',
    device: r,
    en: 'Set the OSPF cost of this interface.',
    hi: 'Interface ki OSPF cost.',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'ip ospf hello-interval 10',
    mode: 'config-if',
    device: r,
    en: 'Set the OSPF hello timer (must match the neighbour).',
    hi: 'Hello timer (neighbour se match).',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'show ip ospf neighbor',
    mode: 'priv',
    device: r,
    en: 'OSPF neighbours and their state (FULL = synced).',
    hi: 'OSPF neighbours aur state.',
    lesson: 'A10',
  },
  {
    topic: 'OSPF',
    example: 'show ip ospf interface gi0/1',
    mode: 'priv',
    device: r,
    en: 'OSPF settings per interface (cost, timers, DR).',
    hi: 'Har interface ki OSPF settings.',
    lesson: 'A10',
  },
  { topic: 'IS-IS', example: 'router isis', mode: 'config', device: r, en: 'Start IS-IS.', hi: 'IS-IS chalu karo.', lesson: 'A10' },
  {
    topic: 'IS-IS',
    example: 'net 49.0001.0000.0000.0001.00',
    mode: 'config-isis',
    device: r,
    en: 'Set the NET (area + system ID).',
    hi: 'NET address (area + system ID).',
    lesson: 'A10',
  },
  {
    topic: 'IS-IS',
    example: 'ip router isis',
    mode: 'config-if',
    device: r,
    en: 'Run IS-IS on this interface.',
    hi: 'Is interface par IS-IS.',
    lesson: 'A10',
  },
  {
    topic: 'IS-IS',
    example: 'show isis neighbors',
    mode: 'priv',
    device: r,
    en: 'IS-IS adjacencies with level (L1/L2).',
    hi: 'IS-IS neighbours aur level.',
    lesson: 'A10',
  },
  {
    topic: 'Services',
    example: 'ip helper-address 10.1.1.53',
    mode: 'config-if',
    device: r,
    en: 'DHCP relay: forward client broadcasts to this server.',
    hi: 'DHCP relay — server tak bhejo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ip nat inside',
    mode: 'config-if',
    device: r,
    en: 'Mark the interface as NAT inside.',
    hi: 'NAT inside interface.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ip nat outside',
    mode: 'config-if',
    device: r,
    en: 'Mark the interface as NAT outside.',
    hi: 'NAT outside interface.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ip nat inside source list 1 interface gi0/2 overload',
    mode: 'config',
    device: r,
    en: 'PAT: translate ACL 1 sources to the Gi0/2 address.',
    hi: 'PAT: ACL 1 ko Gi0/2 address se badlo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'show ip nat translations',
    mode: 'priv',
    device: r,
    en: 'Current NAT/PAT translations.',
    hi: 'NAT translations.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'ntp server 10.1.1.53',
    mode: 'config',
    device: r,
    en: 'Sync the clock from an NTP server.',
    hi: 'NTP server se time lo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'show ntp status',
    mode: 'priv',
    device: r,
    en: 'Is the clock synchronised, at which stratum?',
    hi: 'Clock sync hai? stratum?',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'logging host 10.1.1.100',
    mode: 'config',
    device: r,
    en: 'Send syslog messages to a server.',
    hi: 'Syslog server ko bhejo.',
    lesson: 'A11',
  },
  {
    topic: 'Services',
    example: 'snmp-server enable traps',
    mode: 'config',
    device: r,
    en: 'Send SNMP traps (with snmp-server host).',
    hi: 'SNMP traps bhejo.',
    lesson: 'A11',
  },
  {
    topic: 'Security',
    example: 'access-list 110 deny ip 10.52.50.0 0.0.0.255 10.52.10.0 0.0.0.255',
    mode: 'config',
    device: r,
    en: 'Extended ACL line: block one subnet to another.',
    hi: 'Extended ACL: ek subnet se doosre ko roko.',
    lesson: 'A12',
  },
  {
    topic: 'Security',
    example: 'ip access-group 110 in',
    mode: 'config-if',
    device: r,
    en: 'Apply ACL 110 to packets entering the interface.',
    hi: 'ACL 110 inbound lagao.',
    lesson: 'A12',
  },
  { topic: 'Security', example: 'show access-lists', mode: 'priv', device: r, en: 'List ACLs and their lines.', hi: 'ACLs dikhao.', lesson: 'A12' },
  {
    topic: 'Security',
    example: 'crypto key generate rsa modulus 2048',
    mode: 'config',
    device: r,
    en: 'Create RSA keys for SSH (needs ip domain-name).',
    hi: 'SSH ke liye RSA keys.',
    lesson: 'A11',
  },
  {
    topic: 'Security',
    example: 'transport input ssh',
    mode: 'config-line',
    device: r,
    en: 'Allow only SSH on the vty lines.',
    hi: 'vty par sirf SSH.',
    lesson: 'A12',
  },
  {
    topic: 'Security',
    example: 'login local',
    mode: 'config-line',
    device: r,
    en: 'Use local usernames for vty logins.',
    hi: 'Local usernames se login.',
    lesson: 'A12',
  },
  {
    topic: 'Security',
    example: 'access-class 10 in',
    mode: 'config-line',
    device: r,
    en: 'Only addresses permitted by ACL 10 may log in.',
    hi: 'Sirf ACL 10 wale login kar sakte.',
    lesson: 'A12',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 ip 10.52.10.1',
    mode: 'config-if',
    device: r,
    en: 'HSRP group 10 with this virtual gateway IP.',
    hi: 'HSRP group 10 ka virtual IP.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 priority 110',
    mode: 'config-if',
    device: r,
    en: 'HSRP priority (higher = Active).',
    hi: 'HSRP priority.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 preempt',
    mode: 'config-if',
    device: r,
    en: 'Take the Active role back when better.',
    hi: 'Behtar ho to role wapas lo.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'standby 10 track gi0/1 decrement 20',
    mode: 'config-if',
    device: r,
    en: 'Lower priority by 20 when Gi0/1 goes down.',
    hi: 'Gi0/1 gire to priority 20 kam.',
    lesson: 'A13',
  },
  {
    topic: 'Redundancy',
    example: 'show standby brief',
    mode: 'priv',
    device: r,
    en: 'HSRP groups, priority and state.',
    hi: 'HSRP state.',
    lesson: 'A13',
  },
  {
    topic: 'QoS',
    example: 'class-map match-any VOICE',
    mode: 'config',
    device: r,
    en: 'Create a traffic class.',
    hi: 'Traffic class banao.',
    lesson: 'A14',
  },
  {
    topic: 'QoS',
    example: 'policy-map WAN-OUT',
    mode: 'config',
    device: r,
    en: 'Create a QoS policy (then class / priority / bandwidth).',
    hi: 'QoS policy banao.',
    lesson: 'A14',
  },
  {
    topic: 'QoS',
    example: 'service-policy output WAN-OUT',
    mode: 'config-if',
    device: r,
    en: 'Attach the policy to outgoing traffic.',
    hi: 'Policy outgoing par lagao.',
    lesson: 'A14',
  },
  { topic: 'QoS', example: 'speed 10', mode: 'config-if', device: r, en: 'Force the port speed (Mb/s).', hi: 'Port speed fix karo.', lesson: 'A14' },
  {
    topic: 'Host (PC)',
    example: 'nslookup ju-nms',
    mode: 'host',
    device: pc,
    en: 'Ask the DNS server for a name.',
    hi: 'DNS se naam poochho.',
    lesson: 'A11',
  },
  {
    topic: 'Host (PC)',
    example: 'ssh admin@10.1.1.1',
    mode: 'host',
    device: pc,
    en: 'Open an SSH connection (connection + login check).',
    hi: 'SSH connection kholo.',
    lesson: 'A11',
  },
  {
    topic: 'Host (PC)',
    example: 'ipconfig /renew',
    mode: 'host',
    device: pc,
    en: 'Get a DHCP address again.',
    hi: 'DHCP se address dobara lo.',
    lesson: 'A11',
  },
  {
    topic: 'BGP',
    example: 'router bgp 65000',
    mode: 'config',
    device: r,
    en: 'Start BGP in AS 65000.',
    hi: 'AS 65000 mein BGP chalu.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'bgp router-id 10.0.1.1',
    mode: 'config-bgp',
    device: r,
    en: 'Fix the BGP router-ID (use the loopback).',
    hi: 'BGP router-ID set karo.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 10.0.1.13 remote-as 65000',
    mode: 'config-bgp',
    device: r,
    en: 'Define a neighbour; same AS = iBGP, other AS = eBGP.',
    hi: 'Neighbour banao; same AS = iBGP.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 10.0.1.13 update-source loopback0',
    mode: 'config-bgp',
    device: r,
    en: 'Source the iBGP session from Loopback0 (peer must expect this address).',
    hi: 'iBGP session loopback se.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 10.0.1.13 next-hop-self',
    mode: 'config-bgp',
    device: r,
    en: 'Advertise eBGP-learned routes with this router as next hop.',
    hi: 'Next hop apna address.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 10.0.1.13 route-reflector-client',
    mode: 'config-bgp',
    device: r,
    en: '(on the RR) Make the neighbour a route-reflector client.',
    hi: 'RR client banao.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 192.0.2.2 ebgp-multihop 2',
    mode: 'config-bgp',
    device: r,
    en: 'Allow an eBGP peer that is not directly connected.',
    hi: 'eBGP peer door ho to.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'network 172.16.10.0 mask 255.255.255.0',
    mode: 'config-bgp',
    device: r,
    en: 'Originate a prefix that is in the routing table.',
    hi: 'Prefix BGP mein daalo.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'no bgp default ipv4-unicast',
    mode: 'config-bgp',
    device: r,
    en: 'Do not activate neighbours for IPv4 unicast automatically (VPNv4-only RR).',
    hi: 'IPv4 auto-activate band.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'address-family vpnv4',
    mode: 'config-bgp',
    device: r,
    en: 'Enter the VPNv4 address family (MP-BGP).',
    hi: 'VPNv4 address family.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 10.0.1.13 activate',
    mode: 'config-bgp-vpnv4',
    device: r,
    en: 'Exchange VPNv4 routes with this neighbour.',
    hi: 'VPNv4 routes is neighbour se.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'neighbor 10.0.1.13 send-community extended',
    mode: 'config-bgp-vpnv4',
    device: r,
    en: 'Send route-targets (accepted; RTs are always carried in the simulator).',
    hi: 'RT bhejo.',
    lesson: 'B5',
  },
  {
    topic: 'BGP',
    example: 'show ip bgp summary',
    mode: 'priv',
    device: r,
    en: 'IPv4 BGP neighbours, state and prefixes received; reason below if not Established.',
    hi: 'BGP neighbours ki list.',
    lesson: 'B5',
  },
  { topic: 'BGP', example: 'show ip bgp', mode: 'priv', device: r, en: 'IPv4 BGP table with best paths (>).', hi: 'BGP table.', lesson: 'B5' },
  {
    topic: 'BGP',
    example: 'show bgp vpnv4 unicast all summary',
    mode: 'priv',
    device: r,
    en: 'VPNv4 and VRF (PE–CE) neighbours.',
    hi: 'VPNv4 neighbours.',
    lesson: 'B6',
  },
  {
    topic: 'BGP',
    example: 'show bgp vpnv4 unicast all',
    mode: 'priv',
    device: r,
    en: 'VPNv4 routes grouped by route distinguisher.',
    hi: 'RD ke hisaab se VPN routes.',
    lesson: 'B6',
  },
  {
    topic: 'BGP',
    example: 'show bgp vpnv4 unicast all labels',
    mode: 'priv',
    device: r,
    en: 'Local (in) and remote (out) VPN labels per prefix.',
    hi: 'VPN labels.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'vrf definition UTS',
    mode: 'config',
    device: r,
    en: 'Create a VRF (IOS-XE style; "ip vrf UTS" also works).',
    hi: 'VRF banao.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'rd 10.0.1.1:100',
    mode: 'config-vrf',
    device: r,
    en: 'Route distinguisher: makes this VRF’s prefixes unique in VPNv4.',
    hi: 'RD set karo.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'address-family ipv4',
    mode: 'config-vrf',
    device: r,
    en: 'Enter the VRF’s IPv4 address family.',
    hi: 'VRF IPv4 family.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'route-target both 65000:100',
    mode: 'config-vrf-af',
    device: r,
    en: 'Export and import RT 65000:100.',
    hi: 'RT export aur import.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'route-target import 65000:107',
    mode: 'config-vrf-af',
    device: r,
    en: 'Also import routes tagged 65000:107 (e.g. a shared NMS).',
    hi: 'Extra RT import.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'vrf forwarding UTS',
    mode: 'config-if',
    device: r,
    en: 'Put the interface into VRF UTS (removes its IP address — set it again).',
    hi: 'Interface ko VRF mein daalo.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'ip route vrf RAILNET 0.0.0.0 0.0.0.0 10.105.1.2',
    mode: 'config',
    device: r,
    en: 'Static route inside a VRF.',
    hi: 'VRF ke andar static route.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'redistribute connected',
    mode: 'config-bgp-vrf',
    device: r,
    en: '(address-family ipv4 vrf X) Export the VRF’s connected networks into VPNv4.',
    hi: 'VRF ke connected routes VPN mein.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'neighbor 10.103.13.2 remote-as 65201',
    mode: 'config-bgp-vrf',
    device: r,
    en: '(address-family ipv4 vrf X) PE–CE eBGP neighbour inside the VRF.',
    hi: 'VRF mein CE neighbour.',
    lesson: 'B6',
  },
  { topic: 'L3VPN', example: 'show vrf', mode: 'priv', device: r, en: 'VRFs with RD and interfaces.', hi: 'VRF list.', lesson: 'B6' },
  {
    topic: 'L3VPN',
    example: 'show ip vrf detail UTS',
    mode: 'priv',
    device: r,
    en: 'RD, interfaces and import/export RTs of one VRF.',
    hi: 'VRF ka detail.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'show ip route vrf UTS',
    mode: 'priv',
    device: r,
    en: 'Routing table of one VRF.',
    hi: 'VRF ki routing table.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'ping vrf UTS 10.100.1.10',
    mode: 'priv',
    device: r,
    en: 'Ping from inside a VRF.',
    hi: 'VRF ke andar se ping.',
    lesson: 'B6',
  },
  {
    topic: 'L3VPN',
    example: 'traceroute vrf UTS 10.100.1.10',
    mode: 'priv',
    device: r,
    en: 'Traceroute inside a VRF (core hops show both labels).',
    hi: 'VRF traceroute.',
    lesson: 'B6',
  },
  {
    topic: 'L2VPN',
    example: 'xconnect 10.0.1.13 1301 encapsulation mpls',
    mode: 'config-if',
    device: r,
    en: 'VPWS: carry this port (or dot1Q subinterface) to the peer PE; same VC ID on both sides.',
    hi: 'Port ko peer PE tak pseudowire se.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'no xconnect',
    mode: 'config-if',
    device: r,
    en: 'Remove the pseudowire from the interface.',
    hi: 'Pseudowire hatao.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'mtu 1600',
    mode: 'config-if',
    device: r,
    en: 'Layer-2 MTU of the port; both ends of a pseudowire must match.',
    hi: 'Port ka L2 MTU; dono taraf same.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'l2 vfi CCTV manual',
    mode: 'config',
    device: r,
    en: 'Create a VPLS forwarder (virtual switch).',
    hi: 'VPLS VFI banao.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'vpn id 104',
    mode: 'config-vfi',
    device: r,
    en: 'VPLS ID: becomes the VC ID of every pseudowire of this VFI.',
    hi: 'VFI ka ID (sab PWs ka VC ID).',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'neighbor 10.0.1.13 encapsulation mpls',
    mode: 'config-vfi',
    device: r,
    en: 'Pseudowire to another PE of the VPLS (one per PE: full mesh).',
    hi: 'Doosre PE tak PW (full mesh).',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'xconnect vfi CCTV',
    mode: 'config-if',
    device: r,
    en: 'Attach this port to the VFI (simulator: port-based).',
    hi: 'Port ko VFI se jodo.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'show mpls l2transport vc',
    mode: 'priv',
    device: r,
    en: 'Pseudowires: AC, circuit type, peer, VC ID, status; reason below if DOWN.',
    hi: 'Pseudowires ki list.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'show mpls l2transport vc detail',
    mode: 'priv',
    device: r,
    en: 'Labels, MTU, output interface per pseudowire.',
    hi: 'PW detail: labels, MTU.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'show vfi',
    mode: 'priv',
    device: r,
    en: 'VFIs, attachment ports and pseudowire neighbours.',
    hi: 'VFI aur neighbours.',
    lesson: 'B7',
  },
  {
    topic: 'L2VPN',
    example: 'ping mpls pseudowire 10.0.1.13 1301',
    mode: 'priv',
    device: r,
    en: 'MPLS echo with the VC label: proves the pseudowire end to end.',
    hi: 'Pseudowire ka ping.',
    lesson: 'B7',
  },
  {
    topic: 'TDM PW',
    example: 'controller E1 0/2/0',
    mode: 'config',
    device: ler,
    en: 'Configure a (logical) E1 controller of the NEON LER.',
    hi: 'E1 controller.',
    lesson: 'B8',
  },
  {
    topic: 'TDM PW',
    example: 'cem-group 0 unframed',
    mode: 'config-controller',
    device: ler,
    en: 'Whole E1 as one circuit (SAToP).',
    hi: 'Poora E1 (SAToP).',
    lesson: 'B8',
  },
  {
    topic: 'TDM PW',
    example: 'cem-group 1 timeslots 1-4',
    mode: 'config-controller',
    device: ler,
    en: 'Timeslots 1–4 as a circuit (CESoPSN).',
    hi: 'Timeslots 1–4 (CESoPSN).',
    lesson: 'B8',
  },
  {
    topic: 'TDM PW',
    example: 'interface CEM0/2/0',
    mode: 'config',
    device: ler,
    en: 'Circuit-emulation interface of the controller.',
    hi: 'CEM interface.',
    lesson: 'B8',
  },
  {
    topic: 'TDM PW',
    example: 'cem 0',
    mode: 'config-cem-if',
    device: ler,
    en: 'Select CEM group 0 to attach a pseudowire.',
    hi: 'CEM group chuno.',
    lesson: 'B8',
  },
  {
    topic: 'TDM PW',
    example: 'xconnect 10.0.2.2 2101 encapsulation mpls',
    mode: 'config-if-cem',
    device: ler,
    en: 'Carry the CEM group to the peer PE.',
    hi: 'CEM ko peer tak PW.',
    lesson: 'B8',
  },
  {
    topic: 'TDM PW',
    example: 'show controllers E1 0/2/0',
    mode: 'priv',
    device: ler,
    en: 'CEM groups and their xconnects (logical E1).',
    hi: 'E1 controller status.',
    lesson: 'B8',
  },
];

/** CLI lines that bring a fresh device into `mode` (used by the reference test and the "try it" hint). */
export function preLines(mode: RefMode, device: RefDevice): string[] {
  const port = device === 'router' ? 'gi0/0' : device === 'neon-ler' ? 'gi0/1/0' : device === 'l3-switch' ? 'gi1/0/1' : 'gi0/1';
  switch (mode) {
    case 'user':
    case 'host':
      return [];
    case 'priv':
      return ['enable'];
    case 'config':
      return ['enable', 'configure terminal'];
    case 'config-if':
      return ['enable', 'configure terminal', `interface ${port}`];
    case 'config-vlan':
      return ['enable', 'configure terminal', 'vlan 10'];
    case 'config-router':
      return ['enable', 'configure terminal', 'router ospf 1'];
    case 'config-subif':
      return ['enable', 'configure terminal', 'interface gi0/0.10'];
    case 'config-isis':
      return ['enable', 'configure terminal', 'router isis'];
    case 'config-line':
      return ['enable', 'configure terminal', 'line vty 0 4'];
    case 'config-vrf':
      return ['enable', 'configure terminal', 'vrf definition UTS'];
    case 'config-vrf-af':
      return ['enable', 'configure terminal', 'vrf definition UTS', 'address-family ipv4'];
    case 'config-bgp':
      return ['enable', 'configure terminal', 'router bgp 65000'];
    case 'config-bgp-vpnv4':
      return ['enable', 'configure terminal', 'router bgp 65000', 'neighbor 10.0.1.13 remote-as 65000', 'address-family vpnv4'];
    case 'config-bgp-vrf':
      return ['enable', 'configure terminal', 'vrf definition X', 'rd 1:1', 'exit', 'router bgp 65000', 'address-family ipv4 vrf X'];
    case 'config-vfi':
      return ['enable', 'configure terminal', 'l2 vfi CCTV manual', 'vpn id 104'];
    case 'config-controller':
      return ['enable', 'configure terminal', 'controller E1 0/2/0'];
    case 'config-cem-if':
      return ['enable', 'configure terminal', 'controller E1 0/2/0', 'cem-group 0 unframed', 'exit', 'interface CEM0/2/0'];
    case 'config-if-cem':
      return ['enable', 'configure terminal', 'controller E1 0/2/0', 'cem-group 0 unframed', 'exit', 'interface CEM0/2/0', 'cem 0'];
  }
}
