import {
  Antenna,
  Blocks,
  Box,
  Building2,
  Cloud,
  Cpu,
  Laptop,
  Share2,
  Camera,
  Cctv,
  Combine,
  Construction,
  Container,
  Database,
  HardDrive,
  Layers,
  Monitor,
  Network,
  Phone,
  PhoneCall,
  Rainbow,
  Repeat,
  Route,
  Router,
  Server,
  ServerCog,
  Shield,
  Ticket,
  TrainTrack,
  Truck,
  Waypoints,
  Wifi,
  type LucideIcon,
} from 'lucide-react';
import type { IconKey } from '../model/catalog';

export const DEVICE_ICONS: Record<IconKey, LucideIcon> = {
  mux: Combine,
  sdh: Layers,
  cwdm: Rainbow,
  phone: Phone,
  block: TrainTrack,
  bpac: Blocks,
  logger: HardDrive,
  gate: Construction,
  exchange: PhoneCall,
  pc: Monitor,
  ticket: Ticket,
  freight: Truck,
  ipphone: Antenna,
  camera: Cctv,
  nvr: Camera,
  wifi: Wifi,
  switch: Network,
  l3switch: Waypoints,
  router: Router,
  firewall: Shield,
  nms: ServerCog,
  server: Server,
  ler: Route,
  lsr: Repeat,
  rr: Database,
  hybrid: Container,
  ucpe: Box,
  laptop: Laptop,
  hub: Share2,
  cloud: Cloud,
  division: Building2,
  neonler: Route,
  neonlsr: Cpu,
  vendorler: Route,
  vendorlsr: Repeat,
};

export const CATEGORY_ACCENT: Record<string, string> = {
  legacy: 'text-amber-400 border-amber-700/60',
  lan: 'text-sky-400 border-sky-700/60',
  mpls: 'text-fuchsia-400 border-fuchsia-700/60',
};

